main: main.o
	gcc -o main main.o
main.o: main.c
	gcc -c main.c
qsort: qsort.o
	gcc -o qsort qsort.o
qsort.o: qsort.c
	gcc -c qsort.c
merge: merge.o
	gcc -o merge merge.o
merge.o: merge.c
	gcc -c merge.c
